language: node_js
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
matrix:
  include:
    - node_js: "6"
      env: TZ="America/New_York" FMTS=misc
    - node_js: "8"
      env: TZ="America/Los_Angeles"
    - node_js: "8"
      env: TZ="Europe/London" FMTS=misc
    - node_js: "6"
      env: TZ="Europe/Berlin"
    - node_js: "6"
      env: TZ="Asia/Kolkata" FMTS=misc
    - node_js: "9"
      env: TZ="Asia/Shanghai"
    - node_js: "8"
      env: TZ="Asia/Seoul" FMTS=misc
    - node_js: "7"
      env: TZ="America/Cancun" FMTS=misc

    - node_js: "5"
      env: TZ="America/Anchorage" FMTS=misc
    - node_js: "4"
      env: TZ="America/Barbados" FMTS=misc
    - node_js: "0.12"
      env: TZ="America/Cayman" FMTS=misc
    - node_js: "0.10"
      env: TZ="Pacific/Honolulu" FMTS=misc
    - node_js: "0.8"
      env: TZ="America/Mexico_City" FMTS=misc

before_install:
  - "npm install -g npm@4.3.0"
  - "npm install -g mocha@2.x voc"
  - "npm install blanket"
  - "npm install xlsjs"
  - "npm install coveralls mocha-lcov-reporter"
# note: jsdom 11.x expects node >= 6 but is missing engines.node
  - "npm install jsdom@11.x"
before_script:
  - "make init"
  - "cd test_files; make all; cd -"
after_success:
#  - "make coveralls-spin"
